### ISSUE TITLE
build-and-push-image

### ISSUE THREAD

**Issue by IliaWizy** [IliaWizy/education-app#5]
При запуске workflow, а именно этапов скрипта - build-and-push-image - выдается ошибка. Нужно устранить  или будет висеть до внедрения compose и/или docker registry.

[build-and-push-image](https://github.com/IliaWizy/education-app/actions/runs/7454924054/job/20283149664#step:7:149)

**Comment by sursindmitry** [comment]
Как только мы сделаем Dockerfile для приложения - всё будет работать.
`Error: buildx failed with: ERROR: failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount3318901090/Dockerfile: no such file or directory
`
